Import of FELICITY/Mail-SpamAssassin-3.0.0 from CPAN.
gitpan-cpan-distribution: Mail-SpamAssassin
gitpan-cpan-version:      3.0.0
gitpan-cpan-path:         FELICITY/Mail-SpamAssassin-3.0.0.tar.gz
gitpan-cpan-author:       FELICITY
gitpan-cpan-maturity:     released

diff --git a/build/update_devel b/build/update_devel
--- a/build/update_devel
+++ b/build/update_devel
@@ -1,44 +1,79 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# This script assumes it's being run from the root of the SA code tree
+set -x
 
-WEBDIR=$HOME/spamassassin.taint.org
+umask 002
 
-vers=`build/get_version`				# 2.60-rc3
-minivers=`echo $vers | sed -e 's/-[a-z0-9A-Z]*$//'`	# 2.60
+WEBDIR=$SA_WEBDIR
+test -n "$WEBDIR"  || WEBDIR=$HOME/site
+
+if [ ! -d $WEBDIR ] ; then
+  echo "WARNING: $WEBDIR does not exist" 1>&2
+  echo 1>&2
+fi
+
+GPGSIGN=$SA_GPGSIGN
+test -x "$GPGSIGN" || GPGSIGN=$HOME/sabuildtools/bin/gpgsign
+
+DEVDIR=$WEBDIR/devel
+RELDIR=$WEBDIR/released
+mkdir -p $DEVDIR $RELDIR
+
+DISTNAME=Mail-SpamAssassin
+
+rm -rf $DISTNAME-*               # otherwise make will fail
+
+test -f Makefile && make distclean
+perl Makefile.PL < /dev/null || exit $?
+
+make version.env || exit $?
+. version.env
+
+# $VERSION will be x.y.z for released not marked $IS_DEVEL_BUILD, else
+# x-y-latest while $DIST_VERSION is always the x.y.z variant.
+VERSION=`echo $FULL_VERSION | perl -pe 's/\.\d+(-.*)-r\d+$/-dev/'`
+
+DISTDNAME=$DISTNAME-$DIST_VERSION
+DISTVNAME=$DISTNAME-$VERSION
 
 # delete old CVS files
 find . -name '.#*' -print | xargs rm -f
 
-make clean ; perl Makefile.PL < /dev/null
-make; make; make                # third time lucky!
+make || exit $?
+
 make text_html_doc
 make distcheck
 
-echo $vers > $WEBDIR/latest_version
+echo $VERSION > $WEBDIR/latest_version
 
-rm -f Mail-SpamAssassin-$vers.tar.bz2 Mail-SpamAssassin-$vers.tar.gz Mail-SpamAssassin-$vers.zip
-make tardist
-make zipdist
-gzip -dc Mail-SpamAssassin-$minivers.tar.gz | bzip2 -9c - > Mail-SpamAssassin-$minivers.tar.bz2
+rm -f $DISTVNAME.*
+
+make distdir || exit $?
+tar -cWvf   $DISTVNAME.tar $DISTDNAME         || exit $?
+
+gzip  -f9vc $DISTVNAME.tar > $DISTVNAME.tar.gz  || exit $?
+bzip2 -f9vc $DISTVNAME.tar > $DISTVNAME.tar.bz2 || exit $?
+zip   -rv - $DISTDNAME     > $DISTVNAME.zip     || exit $?
 
 for ext in tar.bz2 tar.gz zip ; do
-  if [ $minivers != $vers ] ; then
-    mv Mail-SpamAssassin-$minivers.$ext Mail-SpamAssassin-$vers.$ext
+  cp $DISTVNAME.$ext $DEVDIR
+
+  build/md5sum.pl $DISTVNAME.$ext > $DEVDIR/$DISTVNAME.$ext.md5  || exit $?
+  build/sha1sum.pl $DISTVNAME.$ext > $DEVDIR/$DISTVNAME.$ext.sha1 || exit $?
+
+  rm -f $DISTVNAME.$ext.asc*
+  if [ -x "$GPGSIGN" ]; then
+    $GPGSIGN $DISTVNAME.$ext                           || exit $?
+    mv $DISTVNAME.$ext.asc $DEVDIR/$DISTVNAME.$ext.asc || exit $?
   fi
 
-  cp Mail-SpamAssassin-$vers.$ext $WEBDIR/devel
-
-  md5sum Mail-SpamAssassin-$vers.$ext \
-	  > $WEBDIR/devel/Mail-SpamAssassin-$vers.$ext.md5
-
-  sha1sum Mail-SpamAssassin-$vers.$ext \
-	  > $WEBDIR/devel/Mail-SpamAssassin-$vers.$ext.sha1
-
-  gpgsign=$HOME/bin/gpgsign
-  rm -f Mail-SpamAssassin-$vers.$ext.asc
-  $gpgsign Mail-SpamAssassin-$vers.$ext
-  mv Mail-SpamAssassin-$vers.$ext.asc $WEBDIR/devel/Mail-SpamAssassin-$vers.$ext.asc
+  rm -f $DISTVNAME.$ext
 done
 
-# ( cd $WEBDIR/devel && cvs add -kb *SpamAssassin* )
+test -f Makefile && make distclean
+rm -f $DISTVNAME.*
 
-ls -l $WEBDIR/devel
+# ( cd $DEVDIR && svn add *SpamAssassin* )
+
+chgrp -R spamassassin $DEVDIR $RELDIR
+ls -l $DEVDIR
